### ISSUE TITLE
fatal error: boost/type_traits/is_fundamental.hpp: No such file or directory

### ISSUE THREAD

**Issue by andrekutianski** [martexcoin/martexcoin#2]
Após `sudo make -f makefile.unix` retorna fatal error. Usando Linux Mint 17

![image](https://user-images.githubusercontent.com/5316107/31512676-34331a56-af62-11e7-9154-fcc60ab8cd08.png)

**Comment by marcianovc** [comment]
qual q versão do teu boost ae ?

OBS: ta seguindo este tutorial aqui [https://martexcoin.org/forum/d/7-compilar-a-wallet-no-linux] , o tutorial foi feito usando Ubuntu 17.04

**Comment by marcianovc** [comment]
instale este pacote aqui:

`sudo apt-get install libboost-all-dev`
