### ISSUE TITLE
socket recv error 10054 - in Windows 10

### ISSUE THREAD

**Issue by zesu2154** [martexcoin/martexcoin#3]
After running for a while, the Windows wallet will have the above socket recv error 10054.

I am connecting an ASIC to solo mine, and after running a while, the error will appears in the debug.log and the coin that was mined disappeared into ether.

**Comment by marcianovc** [comment]
> 
> 
> After running for a while, the Windows wallet will have the above socket recv error 10054.
> 
> I am connecting an ASIC to solo mine, and after running a while, the error will appears in the debug.log and the coin that was mined disappeared into ether.

it is likely that you have mined being out of sync with the network, generating blocks only in your wallet and outside the main network, whenever you are mining make sure everything is fully synchronized
