### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Jetro-Costa** [martexcoin/martexcoin#37]
Minha carteira está com senha, após eu liberar a carteira versão 4.0.2.1 e iniciar a mineração POS, ao mandar o fechamento dá carteira (martex-qt) dá o seguinte erro localizado no arquivo reportar.txt, estou usando bash linux Debian 10, LXDE.
[reportar.txt](https://github.com/martexcoin/martexcoin/files/4741009/reportar.txt)
[debug.log](https://github.com/martexcoin/martexcoin/files/4741010/debug.log)

Segue links de erros semelhantes que encontrei na internet.
https://github.com/bitcoin/bitcoin/issues/9825
https://github.com/monacoinproject/monacoin/issues/17
https://stackoverflow.com/questions/7817161/boostmutexmutex-assertion-pthread-mutex-destroym-failed

**Comment by marcianovc** [comment]
faça o rescan da wallet
