### ISSUE TITLE
Linux wallet requires to manually add nodes

### ISSUE THREAD

**Issue by clementejacques** [martexcoin/martexcoin#4]
Hello, I downloaded the bootstrap to fix the "sync" issues but the wallet installation never booted with the nodes already set up. I manually had to browse them on your blog and add them via terminal. I suppose there could be a way to set them up when installing by default. Thanks!

**Comment by marcianovc** [comment]
This configuration already has by default, this in the file util.cpp

`https://github.com/martexcoin/martexcoin/blob/4c335242c208860a45c9a8bf0532fa5c73795d20/src/util.cpp#L1220`

**Comment by marcianovc** [comment]
`...`
