### ISSUE TITLE
Documentação automática para desenvolver com https://codedocs.xyz/

### ISSUE THREAD

**Issue by Jetro-Costa** [martexcoin/martexcoin#42]
Esta é uma opção para gerar uma documentação online para este repositório.
Segue um exemplo que testei num fork meu https://codedocs.xyz/MarteXcoin-documentation/martexcoin-1/index.html
Aí basta anexar o link no #41 README.md

**Comment by marcianovc** [comment]
#41 merged

**Comment by Jetro-Costa** [comment]
Tens de dar permissão ao  https://codedocs.xyz/ neste repositório para ele gerar a documentação de desenvolvedor.automaticamente.
